// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Z6wgWeYNAehXq_Xa7gIqEI_MxLSJhHU',
    appId: '1:764075652387:web:b42bfdc3dbd821033dc896',
    messagingSenderId: '764075652387',
    projectId: 'truresetx-lite',
    authDomain: 'truresetx-lite.firebaseapp.com',
    storageBucket: 'truresetx-lite.firebasestorage.app',
    measurementId: 'G-JHSV5QGTC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ_Spxc9axV1x3skUCXtSRxurzOsib08A',
    appId: '1:764075652387:android:2cb4db4a8d3548333dc896',
    messagingSenderId: '764075652387',
    projectId: 'truresetx-lite',
    storageBucket: 'truresetx-lite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVgWPRfXwQqP9JlMiHbsImqcw3Brdri08',
    appId: '1:764075652387:ios:0d806803e2631c213dc896',
    messagingSenderId: '764075652387',
    projectId: 'truresetx-lite',
    storageBucket: 'truresetx-lite.firebasestorage.app',
    iosClientId: '764075652387-5paakseem818mdag7hkbhelohujef1f3.apps.googleusercontent.com',
    iosBundleId: 'trureset',
  );

}