import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
// supabase_flutter is not required directly in main; SupabaseService handles
// initialization. Avoid unused imports here.
import 'package:hive_flutter/hive_flutter.dart';
import 'package:firebase_core/firebase_core.dart';
// Generated by `flutterfire configure` (created at lib/firebase_options.dart).
// This file is added to version control by the CLI. It defines
// `DefaultFirebaseOptions.currentPlatform` used below to initialize Firebase.
import 'firebase_options.dart';

import 'core/config/env_runtime.dart';
import 'core/config/env.dart';
import 'app.dart';
import 'features/auth/auth_screen.dart';
// Realtime loader (demo) removed from launcher — keep service implementations elsewhere.
import 'features/settings/settings_screen.dart';
import 'features/mood/mood_tracking_screen.dart';
import 'features/spiritual/spiritual_content_screen.dart';
import 'features/nutrition/food_tracking_screen.dart';
import 'features/nutrition/water_logging_screen.dart';
import 'features/profile/profile_screen.dart';
import 'features/home/enhanced_home_screen.dart';
import 'features/home/home_screen.dart';
import 'features/home/today_dashboard_pro.dart';
import 'features/lists/lists_screen.dart';
import 'features/lists/add_list_screen.dart';
import 'features/devices/device_management_screen.dart';
import 'features/coach/ai_coach_chat_screen.dart';
// Landing screen import removed — app now launches full TruResetXApp by default.
// auth_repository and profile_service are provided via Riverpod elsewhere.
// Avoid importing them directly in main.dart to prevent unused import warnings.
import 'core/services/supabase_service.dart';
import 'core/services/supabase_auth_adapter.dart';
import 'core/services/firebase_auth_adapter.dart';
import 'core/services/clerk_auth_adapter.dart';
import 'core/services/notification_service.dart';

// Storage & sample data
import 'core/services/storage_service.dart';
import 'core/data/sample_data.dart';
import 'data/repositories/list_repository.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load local .env for development (no-op if it doesn't exist).
  await EnvRuntime.init();

  // Initialize Firebase (best-effort). Required for Firestore-backed
  // repositories and Firebase auth. If no Firebase configuration is
  // present, this will be logged and startup will continue.
  try {
    // Initialize with generated platform-specific options. This is the
    // recommended form from the FlutterFire CLI and ensures the correct
    // config is used on each platform.
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    debugPrint('Firebase.initializeApp() succeeded.');
  } catch (e, st) {
    debugPrint('Firebase.initializeApp() failed or not configured: $e\n$st');
  }

  // Initialize Hive for local settings/storage
  await Hive.initFlutter();

  // Initialize app storage boxes (main, lists, items)
  await StorageService.initialize();

  // Ensure settings box is available for toggles like seeding
  final settings = await Hive.openBox('settings');

  // Initialize Supabase service if configured. Supabase is used for
  // data, realtime, and the default auth backend. Guard so missing
  // environment variables don't crash startup.
  final supabaseConfigured = Environment.supabaseUrl.isNotEmpty &&
      Environment.supabaseAnonKey.isNotEmpty &&
      !Environment.supabaseUrl.contains('your-project.supabase.co');
  if (supabaseConfigured) {
    try {
      await SupabaseService.instance.initialize();
      debugPrint('Supabase initialized.');
    } catch (e, st) {
      debugPrint('Supabase initialization failed: $e\n$st');
    }
  } else {
    debugPrint('Supabase not configured; skipping Supabase initialization.');
  }

  // Optional: seed sample wellness lists into the app storage.
  // Controlled by --dart-define=SEED_SAMPLE_DATA=true or Hive key 'seed.sample_data'.
  const seedFlagFromDefine =
      String.fromEnvironment('SEED_SAMPLE_DATA', defaultValue: '') == 'true';
  final seedFlagFromSettings =
      settings.get('seed.sample_data', defaultValue: false) as bool;
  final shouldSeed = seedFlagFromDefine || seedFlagFromSettings;
  if (shouldSeed) {
    try {
      final listRepo = ListRepository();
      final existing = listRepo.getLists();
      if (existing.isEmpty) {
        final samples = SampleData.getSampleLists();
        listRepo.saveLists(samples);
        debugPrint('Seeded ${samples.length} wellness lists into storage.');
      } else {
        debugPrint(
            'Storage already contains ${existing.length} lists; skipping seed.');
      }
    } catch (e, st) {
      debugPrint('Failed to seed sample data: $e\n$st');
    }
  }

  // Initialize local notification service (best-effort)
  try {
    await NotificationService.initialize();
  } catch (e) {
    debugPrint('NotificationService initialization failed: $e');
  }

  // Initialize the selected auth adapter so auth state providers are ready
  // when the UI mounts. The choice is persisted in the `settings` box.
  final backend =
      settings.get('auth_backend', defaultValue: 'supabase') as String;
  switch (backend) {
    case 'firebase':
      // Firebase adapter will call Firebase.initializeApp() internally if needed
      try {
        await FirebaseAuthAdapter.instance.initialize();
        debugPrint('Firebase auth adapter initialized.');
      } catch (e, st) {
        debugPrint('Firebase auth adapter init failed: $e\n$st');
      }
      break;
    case 'clerk':
      try {
        await ClerkAuthAdapter.instance.initialize();
        debugPrint('Clerk auth adapter initialized.');
      } catch (e, st) {
        debugPrint('Clerk auth adapter init failed: $e\n$st');
      }
      break;
    case 'supabase':
    default:
      try {
        // Ensure auth service (supabase) is initialized. This is a no-op
        // if SupabaseService.initialize() already ran above.
        await SupabaseAuthAdapter.instance.initialize();
        debugPrint('Supabase auth adapter initialized.');
      } catch (e, st) {
        debugPrint('Supabase auth adapter init failed: $e\n$st');
      }
  }

  runApp(const ProviderScope(child: AppEntry()));
}

class AppEntry extends StatelessWidget {
  const AppEntry({super.key});

  @override
  Widget build(BuildContext context) {
    // This launcher provides quick access to every top-level screen in the
    // app. It replaces the previous auth-driven home to make it simple to
    // review and test all UI components from one place. If you prefer the
    // original behavior, we can make this conditional behind a debug flag.
    return MaterialApp(
      title: 'TruResetX',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      // Start the full TruResetX app by default so realtime services and
      // auth flows are available on app launch.
      home: const TruResetXApp(),
      routes: {
        '/auth': (_) => const AuthScreen(),
        '/profile_setup': (_) => const ParameterRequiredPlaceholder(
            title: 'Profile Setup',
            message:
                'ProfileSetupScreen requires userId and email. Open from auth flow.'),
        // '/realtime_loader' removed from production launcher.
        '/settings': (_) => const SettingsScreen(),
        '/mood': (_) => const MoodTrackingScreen(),
        '/exercise_ar': (_) => const ParameterRequiredPlaceholder(
            title: 'Exercise AR',
            message:
                'ExerciseARScreen requires exercise and workoutExercise parameters.'),
        '/spiritual': (_) => const SpiritualContentScreen(),
        '/food': (_) => const FoodTrackingScreen(),
        '/water': (_) => const WaterLoggingScreen(),
        '/dashboard': (_) => const ParameterRequiredPlaceholder(
            title: 'Dashboard',
            message: 'UserDashboardScreen requires a UserProfile parameter.'),
        '/profile': (_) => const ProfileScreen(),
        '/home_enhanced': (_) => const EnhancedHomeScreen(),
        '/home': (_) => const HomeScreen(),
        '/lists': (_) => const ListsScreen(),
        '/list_detail': (_) => const ParameterRequiredPlaceholder(
            title: 'List Detail',
            message: 'ListDetailScreen requires a listId parameter.'),
        '/add_list': (_) => const AddListScreen(),
        '/add_item': (_) => const ParameterRequiredPlaceholder(
            title: 'Add Item',
            message: 'AddItemScreen requires a listId parameter.'),
        // Demo routes removed for production launcher.
        '/devices': (_) => const DeviceManagementScreen(),
        '/today': (_) => const TodayDashboardPro(),
        '/ai_coach': (_) => const AICoachChatScreen(),
        '/app': (_) => const TruResetXApp(),
      },
    );
  }
}

class AllScreensLauncher extends StatelessWidget {
  const AllScreensLauncher({super.key});

  static final _items = <Map<String, String>>[
    {'title': 'Auth', 'route': '/auth'},
    {'title': 'Profile Setup', 'route': '/profile_setup'},
    {'title': 'Settings', 'route': '/settings'},
    {'title': 'Mood Tracking', 'route': '/mood'},
    {'title': 'Exercise AR', 'route': '/exercise_ar'},
    {'title': 'Spiritual', 'route': '/spiritual'},
    {'title': 'Food Tracking', 'route': '/food'},
    {'title': 'Water Logging', 'route': '/water'},
    {'title': 'Dashboard', 'route': '/dashboard'},
    {'title': 'Profile', 'route': '/profile'},
    {'title': 'Enhanced Home', 'route': '/home_enhanced'},
    {'title': 'Home', 'route': '/home'},
    {'title': 'Lists', 'route': '/lists'},
    {'title': 'List Detail', 'route': '/list_detail'},
    {'title': 'Add List', 'route': '/add_list'},
    {'title': 'Add Item', 'route': '/add_item'},
    // Demo entries removed from the launcher menu.
    {'title': 'Devices', 'route': '/devices'},
    {'title': 'AI Coach', 'route': '/ai_coach'},
    {'title': 'Full App', 'route': '/app'},
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('TruResetX — All Screens')),
      body: ListView.separated(
        itemCount: _items.length,
        separatorBuilder: (_, __) => const Divider(height: 1),
        itemBuilder: (context, idx) {
          final it = _items[idx];
          return ListTile(
            title: Text(it['title']!),
            trailing: const Icon(Icons.arrow_forward_ios, size: 14),
            onTap: () => Navigator.of(context).pushNamed(it['route']!),
          );
        },
      ),
    );
  }
}

/// Simple placeholder shown when a screen requires runtime parameters.
class ParameterRequiredPlaceholder extends StatelessWidget {
  const ParameterRequiredPlaceholder({
    super.key,
    required this.title,
    required this.message,
  });

  final String title;
  final String message;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(message, textAlign: TextAlign.center),
              const SizedBox(height: 12),
              ElevatedButton(
                onPressed: () => Navigator.of(context).pop(),
                child: const Text('Back'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
