include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
    prefer_single_quotes: true
    sort_constructors_first: false
    sort_unnamed_constructors_first: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
